apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.serviceName }}
  title: ${{ values.serviceName }}
  description: ${{ values.description }}
  tags:
    - ${{ values.language }}
  annotations:
    github.com/project-slug: biniter1/${{ values.serviceName }}
    backstage.io/kubernetes-id: ${{ values.serviceName }}
    backstage.io/kubernetes-namespace: ${{ values.serviceName }}
    argocd/app-name: ${{ values.serviceName }}
spec:
  type: service
  lifecycle: development
  owner: ${{ values.owner }}
  system: online-boutique
