image:
  repository: ghcr.io/biniter1/${{ values.serviceName }}
  tag: latest
  pullPolicy: Always

service:
  port: ${{ values.port }}

replicaCount: ${{ values.replicas }}

resources:
  requests:
    cpu: ${{ values.cpuRequest }}
    memory: ${{ values.memoryRequest }}
  limits:
    cpu: ${{ values.cpuLimit }}
    memory: ${{ values.memoryLimit }}