apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: boutique-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - boutique
  selector:
    matchLabels: {} # Match tất cả services trong namespace boutique
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
