name: CI — cartservice

on:
  push:
    branches: [main]
    paths:
      - 'src/cartservice/**'
      - 'apps/cartservice/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/ci-service.yml
    with:
      service_name: cartservice
      service_path: ./src/cartservice
    secrets: inherit