name: CI Frontend service

on:
  push:
    branches: [main]
    paths:
      - 'src/frontend/**'
      - 'k8s/apps/frontend//**'
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/ci-service.yml
    with:
      service_name: frontend
      service_path: src/frontend
    secrets: inherit 