name: CI — recommendationservice

on:
  push:
    branches: [main]
    paths:
      - 'src/recommendationservice/**'
      - 'apps/recommendationservice/**'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/ci-service.yml
    with:
      service_name: recommendationservice
      service_path: ./src/recommendationservice
    secrets: inherit