name: Deploy to K8S
on:
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: SSH to server 
        
